// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: calc.proto

#include "calc.pb.h"
#include "calc.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

static const char* Calc_method_names[] = {
  "/Calc/Add",
  "/Calc/Sub",
};

std::unique_ptr< Calc::Stub> Calc::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Calc::Stub> stub(new Calc::Stub(channel, options));
  return stub;
}

Calc::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Add_(Calc_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Sub_(Calc_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Calc::Stub::Add(::grpc::ClientContext* context, const ::Ops& request, ::Result* response) {
  return ::grpc::internal::BlockingUnaryCall< ::Ops, ::Result, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Add_, context, request, response);
}

void Calc::Stub::async::Add(::grpc::ClientContext* context, const ::Ops* request, ::Result* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::Ops, ::Result, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Add_, context, request, response, std::move(f));
}

void Calc::Stub::async::Add(::grpc::ClientContext* context, const ::Ops* request, ::Result* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Add_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::Result>* Calc::Stub::PrepareAsyncAddRaw(::grpc::ClientContext* context, const ::Ops& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::Result, ::Ops, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Add_, context, request);
}

::grpc::ClientAsyncResponseReader< ::Result>* Calc::Stub::AsyncAddRaw(::grpc::ClientContext* context, const ::Ops& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncAddRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Calc::Stub::Sub(::grpc::ClientContext* context, const ::Ops& request, ::Result* response) {
  return ::grpc::internal::BlockingUnaryCall< ::Ops, ::Result, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Sub_, context, request, response);
}

void Calc::Stub::async::Sub(::grpc::ClientContext* context, const ::Ops* request, ::Result* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::Ops, ::Result, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Sub_, context, request, response, std::move(f));
}

void Calc::Stub::async::Sub(::grpc::ClientContext* context, const ::Ops* request, ::Result* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Sub_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::Result>* Calc::Stub::PrepareAsyncSubRaw(::grpc::ClientContext* context, const ::Ops& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::Result, ::Ops, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Sub_, context, request);
}

::grpc::ClientAsyncResponseReader< ::Result>* Calc::Stub::AsyncSubRaw(::grpc::ClientContext* context, const ::Ops& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSubRaw(context, request, cq);
  result->StartCall();
  return result;
}

Calc::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Calc_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Calc::Service, ::Ops, ::Result, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Calc::Service* service,
             ::grpc::ServerContext* ctx,
             const ::Ops* req,
             ::Result* resp) {
               return service->Add(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Calc_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Calc::Service, ::Ops, ::Result, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Calc::Service* service,
             ::grpc::ServerContext* ctx,
             const ::Ops* req,
             ::Result* resp) {
               return service->Sub(ctx, req, resp);
             }, this)));
}

Calc::Service::~Service() {
}

::grpc::Status Calc::Service::Add(::grpc::ServerContext* context, const ::Ops* request, ::Result* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Calc::Service::Sub(::grpc::ServerContext* context, const ::Ops* request, ::Result* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


